### ISSUE TITLE
we lost the inet.af domain name

### ISSUE THREAD

**Issue by bradfitz** [bradfitz/tcpproxy#39]
The Taliban apparently seized it in 2024-Jan sometime?

Our bad for using it, even "temporarily", as a joke. Sorry.

We'll change this repo's import path to just be `github.com/inetaf/tcpproxy`

**Comment by AkihiroSuda** [comment]
`inet.af` seems NXDOMAIN now.


> The Taliban apparently seized it in 2024-Jan sometime?

Just to be sure, the reference to the "Taliban" was a joke?
Is there any possibility that an attacker (w/ any affiliation) has ever hosted a malicious version of `inet.af/tcpproxy`?

Is it safe to use this cache?
```
inet.af/tcpproxy v0.0.0-20221017015627-91f861402626 h1:2dMP3Ox/Wh5BiItwOt4jxRsfz
kgyBrHzx2nW28Yg6nc=
inet.af/tcpproxy v0.0.0-20221017015627-91f861402626/go.mod h1:Tojt5kmHpDIR2jMojx
zZK2w2ZR7OILODmUo2gaSwjrk=
```

**Comment by danderson** [comment]
Not a joke as far as we know, no. .af is the country TLD for Afghanistan. See 2021-2024 history at https://en.wikipedia.org/wiki/.af . Allegedly the domain was torched by the ministry of communication, because the registrar failed to make payments (due to international sanctions preventing sending money to the Taliban regime). Whois claims it's still registered and just on administrative hold, but you should assume that `inet.af` is not under control, and likely never will be.

The proxy entries, assuming you're using Google's module cache, should be safe for old cache entries. You should still stop using that module name, since whoever's currently in control of inet.af could start publishing new modules at that URL whenever they like (although it's unlikely to be on their todo list).
